plugin
Added a new plugin repository containing a waze lovelace card.
=> Adds new repository r-renato/ha-card-waze-travel-time

plugin
I'm adding [RGB Light Card](https://github.com/bokub/rgb-light-card) as a default repository
=> Adds new plugin [bokub/rgb-light-card]

appdaemon
This app allows you to make Amazon Alexa speak the time at specified intervals of hourly, half hourly or quarter hourly.
=> Adds new appdaemon [UbhiTS/ad-alexatalkingclock]

integration
Improved backup service for Hass.io that can automatically remove snapshots and supports generational backup schemes.
=> Adds new integration [jcwillox/hass-auto-backup]

integration
This a custom component for Home Assistant. The livebox integration allows you to observe and control Livebox router.
There is currently support for the following device types within Home Assistant:
Sensor with traffic metrics
Binary Sensor with wan status , public ip , private ip
Device tracker for connected devices (via option add wired devices)
Switch for enable/disable Wireless
Service for restart the router
=> Adds new integration [Cyr-ius/hass-livebox-component]

integration
Added Cyr-ius/hass-cozytouch for Cozytouch devices
- Sensor with temperature, occupancy, electricalpower metrics, ...
- Climate sensor with preset mode
- Water Heater sensor with hvac mode , boost mode , wway
=> Adds new integration [Cyr-ius/hass-cozytouch]

appdaemon
Add a new event monitor that places events in specified log locations.
=> Adds new appdaemon [Petro31/ad_monitor_events]

theme
Adding a Home Assistant theme inspired on Google app dark mode to the default repository.
=> Adds new theme [JuanMTech/google_dark_theme]

theme
Adding a Home Assistant theme inspired on Google app light mode to the default repository.
=> Adds new theme [JuanMTech/google_light_theme]

appdaemon
Adds new people tracking sensor.
- [ x] You are submitting only 1 repository.
- [ x] You have tested it with HACS by adding it as a custom repository
=> Adds new appdaemon [Petro31/ad_people_tracker]

appdaemon
`z2m_ikea_controller` repository has been renamed to `controllerx`
=> Rename appdaemon repository z2m_ikea_controller -> controllerx

appdaemon
Adds appdaemon app that creates group.all_* and keeps them up to date with the current integrations and entities.
- [x ] You have tested it with HACS by adding it as a custom repository
=> Adds new appdaemon [Petro31/ad_group_all]

blacklist, integration
PTST/O365Calendar-HomeAssistant has been renamed to PTST/O365-HomeAssistant due to upcoming changes to this integration enabling wider O365 use than just calendars
=> Adds new integration [PTST/O365-HomeAssistant]

appdaemon
You can also :-
add a door sensor (like the Ecolink Door Sensor or any other) to the setup to only ring the bell if the door is currently closed, and has been closed for the last 30 seconds or more. This is so that the bell only rings when someone arrives at your door and not when you step out.
add an outdoor Alexa to greet your guest with a pleasant message based on the time of day
add a doorbell (like the Aeotec Doorbell or any other) to ring when a guest arrives outside your door
=> Adds new appdaemon [UbhiTS/ad-alexadoorbell]

appdaemon
Automatically reboot your internet if you use a Zwave, Zigbee, or Bluetooth switch/socket on your internet modem. This app WILL NOT WORK with WiFi Switches/Sockets
=> Adds new appdaemon [UbhiTS/ad-autointernetrebooter]

appdaemon
This is an AppDaemon App for Home Assistant that is designed to replays your lights behavior when no one is home. There are multiple other approaches out there that try to simulate behavior, which is hard. This approach simply uses your smart devices previous behavior to control their pending behavior.
=> Adds new appdaemon [Mohlsson/ReplayLightsHistory]

integration
This is currently an official HA integration. But it's a web scraper. I'm in the process of publishing to HACS _before_ issuing deprecation PRs to HA-core.
=> Adds new integration [vanstinator/hass-raincloud]

blacklist, integration
Oura Component is removing HACS support as a protest to the decision of deprecating YAML.
You can read more on the [component issue #1](https://github.com/nitobuendia/oura-custom-component/issues/1).
=> Remove HACS support from Oura Component

integration
Group MusicCast Yamaha Speakers with Home Assistant
Overwrite existing pymusiccast module to be able to group musiccast
yamaha speakers.
=> Adds new integration [ppanagiotis/pymusiccast]

integration
=> Adds new integration [deblockt/hass-proscenic-790T-vacuum]

appdaemon
An AppDaemon app to reset Xiaomi Aqara motion sensors after a given timeout.
=> Adds new appdaemon [wernerhp/appdaemon_aqara_motion_sensors]

integration
Hi,
I created a new integration that will allow users to set up webhook automations on events that occur in a user's Zoom account. As an example, I am currently using this integration to enable/disable a `do not disturb` signal for my wife when I enter and exit a Zoom meeting.
I submitted a PR to home-assistant/brands (home-assistant/brands#1804) but it has not been approved yet so that check my fail.
Cheers!
=> Adds new integration [raman325/ha-zoom-automation]

integration
Added a new integration, `eskom_loadshedding`. This integration provides loadshedding-related information pulled from the South African state electricity provider, Eskom.
=> Adds new integration [swartjean/ha-eskom-loadshedding]

plugin
New card which displays Rejseplanen departures in the style of S-Tog departure boards.
=> Adds new plugin [DarkFox/rejseplanen-stog-card]

blacklist, integration, removed
Fixed bugs:
- systemexit causing a full exit/lock of hass
=> Re-add xirixiz / homeassistant-afvalwijzer (fixed bug)

integration
This PR adds the Wibeee component as a default component in HACS
=> Adds new integration [abacao/hass_wibeee]

plugin
Intended to replace [cbulock/lovelace-battery-entity](https://github.com/cbulock/lovelace-battery-entity), which has been removed from HACS due to lack of maintenance. Rewritten and added a few improvements on this card as well.
Many similarities with [maxwroc/battery-state-card](https://github.com/maxwroc/battery-state-card) (which is also derived from cbulock's card), but this card is *a lot* simpler and has a much smaller footprint than maxwroc's, for those who just need a simple battery row in the default entities card.
=> Adds new plugin [benct/lovelace-battery-entity-row]

plugin
it's a visualisation for solar power systems the tesla powerwall style
=> Adds new plugin [reptilex/tesla-style-solar-power-card]

scripts/remove
Ran into an issue when using the `make remove` command to [remove a repo](https://github.com/hacs/default/pull/753). It appears that this is the only mention of `python` (instead of `python3`) left in the scripts.
=> Specify to use python3 in remove script

blacklist, integration, removed
I've gotten my FAA Status integration merged into Home Assistant Core and will be archiving the custom component repo, so this is to remove it from HACS.
=> Remove FAA Status

integration
Hello,
I would like this to be added to deafult repo. 
This is an integration for integrating meross devices in HA without going through their own cloud service (there is already an integration for the latter)
It is already used by a 'bunch' of early adopters and should work just fine
Thank you for your work!
Davide
=> Adds new integration [krahabb/meross_lan]

blacklist, integration, removed
Remove shbatm/hacs-isy994 integration from default.
This integration was used for beta testing changes to the core integration up until HA 2021.6.0; there are breaking changes in 2021.6.8 which will cause issues if people continue to use this branch.
See https://github.com/home-assistant/core/issues/53969 and https://github.com/home-assistant/core/issues/53984
=> Remove 'shbatm/hacs-isy994' from Integrations

integration
Please add my custom component for extending gree climate components with swing mode service.
As it is using the builtin gree integration, wheel and brands tests were disabled in the automatic workflow checks.
=> Adds new integration [mullerdavid/hass_GreeExt]

integration
This integration allows configuration of various Hilo smart home devices. Hilo is a subsidiary of Hydro Quebec. There's already a small community using this integration, it would make the life easier for everyone if we could include it in the default HACS repositories.
=> Adds new integration [dvd-dev/hilo]

integration
Peltec is just one boiler produced by centrometal. Support for other boilers has been added. So it makes sense to rename it from peltec to centrometal-boiler now.
=> Adds new integration [9a4gl/hass-centrometal-boiler]

integration
Adding an integration to read power consumption from Echelon/NES power meters through a Dabbler.dk MEP module.
=> Adds new integration [jnxxx/homeassistant-dabblerdk_powermeterreader]

appdaemon
Add's a new appdaemon app, which is used to connect home assistant with a custom UI for Sonoff NSPanel.
https://github.com/joBr99/nspanel-lovelace-ui
=> Adds new appdaemon [joBr99/nspanel-lovelace-ui]

blacklist, plugin, removed
**Link to successful hassfest action (if integration):**  
Remove SNoof85/lovelace-tempometer-gauge-card as I will not maintain anymore and repo is archived.
=> Remove SNoof85/lovelace-tempometer-gauge-card

blacklist, integration, removed
Looks like the integration is removed by it's author and no longer accessible:
```txt
<Integration fred-oranje/rituals-genie> GitHub returned 404 for https://api.github.com/repos/fred-oranje/rituals-genie
```
https://github.com/fred-oranje/rituals-genie
https://github.com/fred-oranje
Closes hacs/integration#2748
=> Remove fred-oranje/rituals-genie

blacklist, integration, removed
**Link to successful HACS action:** NA  
**Link to successful hassfest action (if integration):** NA
HomeWizard has been added to core since 2022.2. This custom integration was kept alive to make migrations possible but is currently only causing confusion. Let's remove it. 
https://github.com/DCSBL/ha-homewizard-energy
https://www.home-assistant.io/integrations/homewizard/
=> Remove HomeWizard Energy integration

plugin
"mattieha/slider-button-card" has become abandoned and there have been no responses from the maintainer for the past several months. @lizsugar and I are now maintaining a new fork at "custom-cards/slider-button-card" with bug fixes (done) and new features to come shortly.
https://github.com/hacs/default/pull/1388 removes the original version of the card.
**Link to successful HACS action: https://github.com/custom-cards/slider-button-card/runs/6714759995?check_suite_focus=true  
**Link to successful hassfest action (if integration): N/A
=> Adds new plugin [custom-cards/slider-button-card]

blacklist, plugin, removed
"mattieha/slider-button-card" has become abandoned and there have been no responses from the maintainer for the past several months. @lizsugar and I are now maintaining a new fork at "custom-cards/slider-button-card" with bug fixes (done) and new features to come shortly.
**Link to successful HACS action: N/A
**Link to successful hassfest action (if integration): N/A
=> Remove plugin [mattieha/slider-button-card]

integration
This integration gets the list of connected devices to a ZTE F6640 router.
**Link to successful HACS action:**  https://github.com/juacas/zte_tracker/actions/runs/3087929028
**Link to successful hassfest action (if integration):**  https://github.com/juacas/zte_tracker/actions/runs/3087929022
=> Adds new integration [juacas/zte_tracker]

blacklist, removed, theme
**Link to successful HACS action:**  n/a
**Link to successful hassfest action (if integration):**  n/a
Remove the Outline theme from HACS. The feature the theme brought, is now default in HA. The theme shipped a NOOP release a couple of months ago, now it is time to  clean it up. The upstream repository has been archived.
../Frenck
=> Remove deprecated Outline theme

blacklist, integration, removed
**Link to successful HACS action:**  n/a
**Link to successful hassfest action (if integration):**   n.a
This PR removed the custom Litter-Robot integration, for which the upstream repository has been archived after I've raised an issue.
Ref: https://github.com/natekspencer/hacs-litterrobot/issues/17
../Frenck
=> Remove archived Litter-Robot

blacklist, integration, removed
**Link to successful HACS action:**  n/a
**Link to successful hassfest action (if integration):**  n/a
Remove the Renault integration from HACS.
The Renault integration was originally merged into core in 2021.8 and finalised in 2021.10.
The use of the custom component has been deprecated since February 2022 (https://github.com/hacf-fr/hassRenaultZE/pull/155), now it is time to clean it up.
The upstream repository has been archived.
=> Remove archived Renault integration

blacklist, integration, removed
Remove echoromeo/hanobo because it has been replaced by an official integration: https://www.home-assistant.io/integrations/nobo_hub/
=> Remove echoromeo/hanobo

blacklist, integration, removed
Link to current release: <https://github.com/andrew-codechimp/HA-Mastodon-Profile-Stats/releases/tag/1.0.11>
Link to successful HACS action (without the `ignore` key): <https://github.com/andrew-codechimp/HA-Mastodon-Profile-Stats/actions/runs/10692754992/job/29641754136>
Link to successful hassfest action (if integration): <https://github.com/andrew-codechimp/HA-Mastodon-Profile-Stats/actions/runs/10692754992/job/29641754360>
=> Remove andrew-codechimp/HA-Mastodon-Profile-Stats

.github/workflows/checks.yml, scripts/check/releases.py
This has been a requirement for a long time, as I would not add any new without it.
But it was never automatically checked, so mistakes were easy to make.
=> Add a check for releases

blacklist, removed
The repository is no longer archived, and it is the next one of the plugins to be added.
=> Allow marcokreeft87/room-card again

plugin
Link to current release: <https://github.com/DFranzen/Simple-Universal-Touchpad-for-Homeassistant/releases/tag/v0.2>
Link to successful HACS action (without the `ignore` key): <https://github.com/DFranzen/Simple-Universal-Touchpad-for-Homeassistant/actions/runs/15620480051>
=> Adds new plugin [DFranzen/Simple-Universal-Touchpad-for-Homeassistant]

plugin
- [N/A] (For integrations only) I've added the [hassfest action](https://developers.home-assistant.io/blog/2020/04/16/hassfest/) to my repository.
Link to current release: <https://github.com/microteq/extended-gauge/releases/tag/v0.1.0-HACS>
Link to successful HACS action (without the `ignore` key): <https://github.com/microteq/extended-gauge/actions/runs/15849941715>
Link to successful hassfest action (if integration): <N/A>
=> Adds new plugin [microteq/extended-gauge]

plugin
Link to current release: https://github.com/cataseven/Strip-Card/releases/tag/v1.0.0
Link to successful HACS action (without the `ignore` key): https://github.com/cataseven/Strip-Card/actions/runs/16314923820
Link to successful hassfest action (if integration): https://github.com/cataseven/Strip-Card/actions/runs/16314923820
=> Adds new plugin [cataseven/Strip-Card]

plugin
Link to current release: <https://github.com/Rishi8078/TimeFlow-Card/releases/tag/v1.0.0>
Link to successful HACS action (without the `ignore` key): <https://github.com/Rishi8078/TimeFlow-Card/actions/workflows/validate.yaml>
Link to successful hassfest action (if integration): <N/A - This is a plugin>
**Repository:** https://github.com/Rishi8078/TimeFlow-Card
**Type:** Plugin (Dashboard)
**Description:** A beautiful countdown timer card for Home Assistant with animated progress circle and intelligent time formatting.
**Features:**
- Animated SVG progress circle with dynamic scaling
- Smart time display with natural language formatting
- Card-mod compatibility for advanced styling
- Entity support for dynamic countdowns
- Cross-platform date parsing
**Repository Requirements:**
- ✅ Public …
=> Adds new plugin [Rishi8078/TimeFlow-Card]

integration
add ovh_ipv6 integration to integrations
Link to current release: <https://github.com/Elijaht-dev/ovh_ipv6/releases/tag/v2.0.4>
Link to successful HACS action (without the `ignore` key): <https://github.com/Elijaht-dev/ovh_ipv6/actions/runs/16607497120/job/46982955119>
Link to successful hassfest action (if integration): <https://github.com/Elijaht-dev/ovh_ipv6/actions/runs/16607497120/job/46982955168>
=> Adds new integration [Elijaht-dev/ovh_ipv6]

plugin
Embedded View Card for Home Assistant
Repository : https://github.com/redkanoon/embedded-view-card
Link to current release: <https://github.com/redkanoon/embedded-view-card/releases/tag/v1.2.5>
Link to successful HACS action (without the `ignore` key): <https://github.com/redkanoon/embedded-view-card/actions/runs/16815821465>
=> Adds new plugin [redkanoon/embedded-view-card]

integration
A custom integration for Home Assistant that enables communication with Sabiana Smart Energy heat recovery units over Modbus (RTU or TCP). This integration provides access to diagnostic data, environmental sensors, fan status, and control over various operational parameters.
Link to current release: <https://github.com/CMGeorge/homeassistant_sabiana_smart_energy/releases/tag/1.0.2>
Link to successful HACS action (without the `ignore` key): <https://github.com/CMGeorge/homeassistant_sabiana_smart_energy/actions/runs/17783736785/job/50565191768>
Link to successful hassfest action (if integration): <https://github.com/CMGeorge/homeassistant_sabiana_smart_energy/actions/runs/17790348208>
=> Adds new integration [CMGeorge/homeassistant_sabiana_smart_energy]

integration
Add Red Energy integration
Link to current release: <https://github.com/craibo/ha-red-energy-au/releases/tag/1.5.8>
Link to successful HACS action (without the `ignore` key): <https://github.com/craibo/ha-red-energy-au/actions/runs/18303160001/job/52114798198>
Link to successful hassfest action (if integration): <https://github.com/craibo/ha-red-energy-au/actions/runs/18303160001/job/52114798198>
=> Adds new integration [craibo/ha-red-energy-au]
