hacs/default

integration

Adds new integration [slesinger/slesinger]

---

plugin

Adds new plugin [PiotrMachowski/Home-Assistant-Lovelace-Local-Conditional-card]

---

plugin

Adds new plugin [royto/logbook-card]

---

plugin

Adds new plugin [iantrich/roku-card]

---

plugin

Adds new plugin [iantrich/restriction-card]

---

plugin

Adds new plugin [iantrich/radial-menu]

---

plugin

Adds new plugin [iantrich/config-template-card]

---

plugin

Adds new plugin [iantrich/podcast-card]

---

plugin

Adds new plugin [thomasloven/lovelace-card-tools]

---

integration

Adds new integration [lindell/home-assistant-tv4-play]

---

plugin

Adds new plugin [au190/au190_thermostat_card]

---

plugin

Adds new plugin [thomasloven/lovelace-auto-entities]

---

plugin

Adds new plugin [iantrich/aftership-card]

---

integration

Adds new integration [ptimatth/GeorideHA]

---

integration

Adds new integration [basnijholt/media_player.kef]

---

plugin

Adds new plugin [hasl-platform/lovelace-hasl-departure-card]

---

plugin

Adds new plugin [hasl-platform/lovelace-hasl-traffic-status-card]

---

integration

Adds new integration [freakshock88/hass-populartimes]

---

plugin

Adds new plugin [thomasloven/lovelace-layout-card]

---

plugin

Adds new plugin [thomasloven/lovelace-more-info-card]

---

theme

Adds new theme [naofireblade/clear-theme]

---

theme

Adds new theme [naofireblade/clear-theme-dark]

---

integration

Added custom integration shogunxam/Home-Assistant-custom-components-cfr-toscana

Adds new integration [shogunxam/Home-Assistant-custom-components-cfr-toscana]

---

integration

Adds new integration [thomasloven/hass-fontawesome]

---

appdaemon

Adds new appdaemon [xaviml/z2m_ikea_controller]

---

theme

Adds new theme [basnijholt/lovelace-ios-dark-mode-theme]

---

integration

Adds new integration [fineemb/Yeelink-ven-fan]

---

integration

Adds new integration [gcobb321/icloud3]

---

theme

Adds new theme [kethoth/green_slate_theme]

---

integration

Adds new integration [claudegel/sinope-130]

---

integration

Adds new integration [tomaae/homeassistant-mikrotik_router]

---

integration

Adds new integration [remco770/garbage-bar-homeassistant]

---

theme

Adds new theme [Poeschl/slate_red]

---

integration

Cover integration for controlling Hunter Douglas blinds

Adds new integration [safepay/cover.hd_powerview]

---

integration

Adds new integration [zachowj/hass-node-red]

---

integration

Adds new integration [DarkSir23/sensor.mylar]

---

plugin

Adds new plugin [fineemb/lovelace-fan-xiaomi]

---

plugin

Adds new plugin [thomasloven/lovelace-state-switch]

---

theme

Think we got all the checks covered

Adds new theme [estiens/sweet_pink_hass_theme]

---

integration

Adds new integration [pinkywafer/Calendarific]

---

appdaemon

Add aneisch/follow_me_appdaemon
- [ X ] You are submitting only 1 repository.
- [ X ] You repository is compliant with https://hacs.xyz/docs/publish/start
- [ X ] You have tested it with HACS by adding it as a custom repository

Adds new appdaemon [aneisch/follow_me_appdaemon]

---

integration

Hi,
this is to add my integration of Home Connect:
https://github.com/DavidMStraub/homeassistant-homeconnect/
Thanks!

Adds new integration [DavidMStraub/homeassistant-homeconnect]

---

plugin

Adds new plugin [maykar/custom-header]

---

blacklist
plugin

Adds new blacklist [maykar/compact-custom-header]

---

integration

Adds new integration [briis/mbweather]

---

plugin

Adds new plugin [Anonym-tsk/lovelace-starline-card]

---

integration

Adds new integration [briis/smartweather]

---

integration

Adds new integration [doudz/homeassistant-myjdownloader]

---

appdaemon

Add a new AppDaemon app.
- [ x ] You are submitting only 1 repository.
- [ x ] You repository is compliant with https://hacs.xyz/docs/publish/start
- [ x ] You have tested it with HACS by adding it as a custom repository

Adds new appdaemon [Burningstone91/Hue_Dimmer_Deconz]

---

integration

Adds new integration [thevoltagesource/LennoxiComfort]

---

integration

Adds new integration [cyberjunky/home-assistant-toon_climate]

---

integration

Adds new integration [cyberjunky/home-assistant-toon_smartmeter]

---

integration

Adds new integration [cyberjunky/home-assistant-toon_boilerstatus]

---

integration

Adds new integration [cyberjunky/home-assistant-p2000]

---

integration

Adds new integration [cyberjunky/home-assistant-arpscan_tracker]

---

integration

Adds new integration [cyberjunky/home-assistant-plugwise]

---

integration

Adds new integration [cyberjunky/home-assistant-hvcgroep]

---

integration

Adds new integration [cyberjunky/home-assistant-ttn_gateway]

---

integration

Adds new integration [rsnodgrass/hass-adtpulse]

---

integration

Added rsnodgrass/hass-flo-water for Flo water control devices

Adds new integration [rsnodgrass/hass-flo-water]

---

integration

Added rsnodgrass/hass-sensorpush

Adds new integration [rsnodgrass/hass-sensorpush]

---

integration

Adds new integration [bacco007/sensor.waternsw]

---

appdaemon

Adds new appdaemon [jmarsik/ad-eurotronic-trv-valvepos]

---

integration

Adds new integration [briis/unifiprotect]

---

integration

Adds new integration [dr1rrb/ha-twinkly]

---

theme

Adds new theme [aFFekopp/dark_teal]

---

theme

Adds new theme [arsaboo/oxford_blue_theme]

---

integration

Adds new integration [burnnat/ha-polar]

---

integration

Adds new integration [burnnat/ha-hdhomerun]

---

plugin

Adds new plugin [ikaruswill/lovelace-fan-xiaomi]

---

plugin

Adds new plugin [thomasloven/lovelace-template-entity-row]

---

integration

Adds new integration [arjenvrh/audi_connect_ha]

---

theme

Adds new theme [aFFekopp/noctis]

---

appdaemon

Adds new appdaemon [benleb/ad-ench-ad3]

---

integration

Adds new integration [PTST/O365Calendar-HomeAssistant]

---

plugin

Adds new plugin [finity69x2/light-brightness-preset-row]

---

appdaemon

Adding 'IllluminateDoor' appdaemon app.

Adds new appdaemon [Petro31/IlluminateDoor]

---

theme

Adding my custom sundown theme to default theme repositories.

Adds new theme [am80l/sundown]

---

integration

Adds new integration [shutupflanders/sensor.moneydashboard]

---

integration

Adds new integration [ReneNulschDE/mbapipy]

---

python_script

Adds new python_script [kodi1/tracker_merge]

---

integration

Adds new integration [kodi1/darksky_m]

---

integration

Adds new integration [kodi1/esp_wd]

---

integration

Adds new integration [kodi1/tvh_rec]

---

integration

Adds new integration [Sholofly/ZiggoNext]

---

integration

Adds new integration [kodi1/meteoalarm]

---

integration

Adds new integration [kodi1/songpal_m]

---

integration

Adds new integration [AdamNaj/linksys_velop]

---

appdaemon

Runs sql commands to tidy up a GTFS file for specific stops for use with HA.

Adds new appdaemon [simonhq/Clean-GTFS]

---

integration

Adds new integration [JAAlperin/hass-bardolph]

---

integration

Adds new integration [vinteo/hass-opensprinkler]

---

integration

Adds new integration [so3n/HA_harmony_climate_component]

---

theme

A Dark Theme for Home Assistant

Adds new theme [78wesley/Darkish-Theme]

---

integration

Adds new integration [dlarrick/hass-kumo]

---

theme

Adds new theme [JuanMTech/amoled_blue]

---

integration

Adds new integration [AaronDavidSchneider/SonosAlarm]

---

appdaemon

Adds new appdaemon [AaronDavidSchneider/SonosAlarmAutomation]

---

theme

- [v] You are submitting only 1 repository.
- [v] You repository is compliant with https://hacs.xyz/docs/publish/start
- [v] You have tested it with HACS by adding it as a custom repository

Adds new theme [fi-sch/ux_goodie_theme]

---

appdaemon

Adds new appdaemon [so3n/Bring-Back-group.all_x]

---

theme

Adds new theme [sinclairpaul/ha_purple_theme]

---

integration

Adds new integration [Limych/ha-iaquk]

---

theme

Adds new theme [houtknots/UglyChristmas-Theme]

---

blacklist
integration

Adds new blacklist [basnijholt/media_player.kef]

---

appdaemon

Adds new appdaemon [so3n/Appdaemon-Xiaomi-Doorbell]

---

integration

Adds new integration [Armaell/home-assistant-custom-icons-loader]

---

appdaemon

Adds new appdaemon [so3n/Appdaemon-Xiaomi-Smart-Button]

---

theme

Adds new theme [basnijholt/lovelace-ios-light-mode-theme]

---

appdaemon

Adds new appdaemon [vash3d/nethassmo]

---

theme

Adds new theme [chaptergy/noctis-grey]

---

plugin

Adds new plugin [chaptergy/lightalarm-card]

---

integration

Adds new integration [cgarwood/homeassistant-zwave_mqtt]

---

integration

Repository: https://github.com/amelchio/logbook_cache

Adds new integration [amelchio/logbook_cache]

---

theme

Adds new theme [JuanMTech/green_dark_mode]

---

theme

Adds new theme [JuanMTech/green_light_mode]

---

theme

Adds new theme [JuanMTech/orange_dark]

---

theme

Adds new theme [JuanMTech/orange_light]

---

integration

Add new integration burnnat/ha-fitness-push

Adds new integration [burnnat/ha-fitness-push]

---

appdaemon

- [x ] You have tested it with HACS by adding it as a custom repository

Adds new appdaemon [Petro31/ad_convert_media_volume]

---

appdaemon

- [x ] You have tested it with HACS by adding it as a custom repository

Adds new appdaemon [Petro31/ad_multizone_media_control]

---

theme

Adds new theme [hekm77/reeder_dark_theme]

---

integration

Adds new integration [elad-bar/ha-blueiris]

---

integration

Adds new integration [heyajohnny/afvalinfo]

---

integration

Adds new integration [peetereczek/ztm]

---

appdaemon

Adds new appdaemon [Petro31/ad_who_used_the_door]

---

appdaemon

Adds new appdaemon [Petro31/ad_simple_door_bell]

---

appdaemon

Adds new appdaemon [Petro31/ad_toggle_light]

---

integration

Adds new integration [fineemb/Xiaomi-Smart-Multipurpose-Kettle]

---

plugin

Adds new plugin [sbryfcz/harmony-card]

---

plugin

Adds new plugin [dooz127/swipe-glance-card]

---

integration

Adds new integration [ryanmac8/Home-Assistant-Marta]

---

integration

Adds new integration [bacco007/sensor.opennem]

---

appdaemon

Adds new appdaemon [Petro31/ad_seasonal_lights]

---

plugin

Adds new plugin [fineemb/lovelace-thermostat-card]

---

integration

Adds new integration [tuxuser/abfallapi_regioit_ha]

---

integration

Adds new integration [edenhaus/ha-prosenic]

---

plugin

Adds new plugin [peetereczek/ztm-stop-card]

---

integration

Adds new integration [elad-bar/ha-dahuavto]

---

integration

Adds new integration [ntilley905/faastatus]

---

README.md

Note: Steps above are N/A. I've allowed edits from maintainers, so changes can be made without me.

Fix link to default repositories

---

integration
plugin

Adds new integration [fineemb/Smartmi-smart-heater]

---

integration

add Home-Is-Where-You-Hang-Your-Hack/sensor.goveetemp_bt_hci
- [ X] You are submitting only 1 repository.
- [ X] You repository is compliant with https://hacs.xyz/docs/publish/start
- [ X] You have tested it with HACS by adding it as a custom repository.
- [ X] The list are still alphabetical after my change.

Adds new integration [Home-Is-Where-You-Hang-Your-Hack/sensor.goveetemp_bt_hci]

---

integration

Adds new integration [And3rsL/Deebot-for-hassio]

---

integration

This component is used for control Freebox Player by calling intern API to simulate remote

Adds new integration [Pouzor/freebox_player]

---

integration

Adds new integration [Johnwulp/rad-afval]

---

integration

Adds new integration [ryannazaretian/hacs-nexia-climate-integration]

---

integration

Adds new integration [And3rsL/VisonicAlarm-for-Hassio]

---

integration

German müllabfuhr sensor (provider: Jumomind)

Adds new integration [tuxuser/abfallapi_jumomind_ha]

---

integration

Adds new integration [Poeschl/Remote-PicoTTS]

---

plugin

Adds new plugin [fineemb/lovelace-dc1-card]

---

integration

Adds new integration [jaruba/ha-samsungtv-tizen]

---

integration

Home Assistant sensor for german AWB waste collection schedule

Adds new integration [jensweimann/awb]

---

plugin

Adds new plugin [ofekashery/vertical-stack-in-card]

---

python_script

Adds new python_script [pmazz/ps_hassio_entities]

---

integration

Adds new integration [lindell/home-assistant-svt-play]

---

appdaemon

Adds new appdaemon [Odianosen25/Monitor-App]

---

integration

Adds new integration [websylv/homeassistant-meteoswiss]

---

integration

Adds new integration [maykar/plex_assistant]

---

integration

Adds new integration [kuchel77/diskspace]

---

integration

Adds new integration [binsentsu/home-assistant-solaredge-modbus]

---

integration

Adds new integration [zha-ng/zha-map]

---

integration

Adds new integration [dmitry-k/yandex_smart_home]

---

integration

Adds new integration [OpenXbox/xboxone-home-assistant]

---

plugin

Adds new plugin [sdelliot/pie-chart-card]

---

integration

Adds the custom component [lichtteil/local_luftdaten](https://github.com/lichtteil/local_luftdaten/).

Adds new integration [lichtteil/local_luftdaten]

---

appdaemon

Adds new appdaemon [haberda/update_lights]

---

plugin

Adds new plugin [jcwillox/lovelace-paper-buttons-row]

---

plugin

Adds new plugin [cbulock/lovelace-battery-entity]

---

integration

Adds new integration [twrecked/hass-virtual]

---

netdaemon

Adds new netdaemon [hacs/ND-NotifyUpdates]

---

netdaemon

Adds new netdaemon [isabellaalstrom/ND-MotionSnapshot]

---

plugin

Adds new plugin [jcwillox/lovelace-canary]

---

integration

Adds new integration [KoljaWindeler/ics]

---

python_script

Adds new python_script [Santobert/HA-UpdateClimate]

---

integration

Adds new integration [SLG/home-assistant-whatpulse]

---

plugin

Adds new plugin [marrobHD/rotel-card]

---

integration

Adds new integration [jonkristian/wasteplan_trv]

---

plugin

Adds new plugin [Savjee/button-text-card]

---

plugin

Adds new plugin [faeibson/lovelace-multiline-text-input-card]

---

integration

Adds new integration [Hellowlol/ha-tide]

---

integration

The integration listens to game state changes of CS:GO and emits events in HomeAssistant to e.g. control lights based on the game state

Adds new integration [lociii/homeassistant-csgo]

---

integration

Adds new integration [mikelawrence/senseme-hacs]

---

integration

Adds new integration [sermayoral/ha-samsungtv-encrypted]

---

plugin

Adds new plugin [gadgetchnnel/lovelace-card-preloader]

---

appdaemon

Adds new appdaemon [badguy99/octoblock]

---

appdaemon

Adds new appdaemon [badguy99/octocost]

---

appdaemon

Adds new appdaemon [haberda/light_automation]

---

integration

Adds new integration [ITTV-tools/homeassistant-kostalplenticore]

---

integration

Added "rsnodgrass/hass-poolmath" integration
- [X ] You are submitting only 1 repository.
- [X ] You repository is compliant with https://hacs.xyz/docs/publish/start
- [X ] You have tested it with HACS by adding it as a custom repository.
- [X ] The list are still alphabetical after my change.

Adds new integration [rsnodgrass/hass-poolmath]

---

theme

Adds new theme [Nihvel/your_name]

---

integration

Adds new integration [joogps/MQTT-Climate-Sync]

---

integration

Adds new integration [ollo69/ha-samsungtv-smart]

---

plugin

- [ x] You repository is compliant with https://hacs.xyz/docs/publish/start
- [ x] You have tested it with HACS by adding it as a custom repository.
- [ x] The list are still alphabetical after my change.

Adds new plugin [finity69x2/binary-control-button-row]

---

integration

Adds new integration [eifinger/hass-foldingathomecontrol]

---

integration

Adds new integration [opravdin/weback-hass]

---

theme

Adds new theme [Banditen01/vintage_theme]

---

integration

Adds new integration [elad-bar/ha-edgeos]

---

integration

this adds the noonlight integration for HomeAssistant developed by Konnected

Adds new integration [konnected-io/noonlight-hass]

---

integration

Add FKF Budapest Garbage Collection custom component.

Adds new integration [amaximus/fkf-garbage-collection]

---

plugin

Add FKF Garbage Collection custom card

Adds new plugin [amaximus/fkf-garbage-collection-card]

---

.github/workflows/validate.yaml

Add HACS Action

---

integration

Adds new integration [ericpignet/home-assistant-tplink_router]

---

integration

Adds new integration [lukich48/hass_mqtt_template_switch]

---

python_script

Adds new python_script [iml885203/HA-FanSpeedControl]

---

integration

Add new integration r-renato/ha-climacell-weather

Adds new integration [r-renato/ha-climacell-weather]

---

plugin

Adds new plugin [Sian-Lee-SA/honeycomb-menu]

---

integration

Added Youless LS110 integration

Adds new integration [rkoebrugge/hacs-youless-component]

---

integration

Adds new integration [peternijssen/home-assistant-jumbo]

---

plugin

Adds new plugin [Voxxie/lovelace-jumbo-card]

---

integration

Adds new integration [Bouni/drkblutspende]

---

appdaemon

Set Temp Limits, Enforce Fan Modes, Door/Window Shut Off, Daily Shut Off and Air Cycle makes your thermostat a genius with Alexa's voice

Adds new appdaemon [UbhiTS/ad-alexasmarttalkingthermostat]

---

integration

Adds new integration [robbinjanssen/home-assistant-omnik-inverter]

---

plugin

Adds new plugin [marksie1988/atomic-calendar-revive]

---

integration

Adds new integration [Bouni/luxtronik]

---

integration

Adds new integration [freol35241/ltss]

---

integration

Set attributes for motion sensor
Change refresh intervall

Adds new integration [Cyr-ius/hass-hue-service-advanced]

---

integration

Adds new integration [gcorgnet/sensor.emby_upcoming_media]

---

plugin

Adds new plugin [fineemb/lovelace-air-filter-card]

---

integration

Adds new integration [msp1974/homeassistant-jlrincontrol]

---

plugin

Link: https://github.com/denysdovhan/vacuum-card

Adds new plugin [denysdovhan/vacuum-card]

---

plugin

Adds new plugin [Imbuzi/meteo-france-weather-card]

---

integration

Adds new integration [nagyrobi/home-assistant-custom-components-cover-rf-time-based]

---

integration

Adds new integration [youdroid/home-assistant-couchpotato]

---

plugin

Adds new plugin [GeorgeSG/lovelace-time-picker-card]

---

integration

Adds new integration [cagnulein/switchbot_press]

---

integration

Adds new integration [pfunkmallone/HACS-camect-integration]

---

appdaemon

Adds new appdaemon [Petro31/ad_count_entities]

---

plugin

Adds new plugin [clayauld/lovelace-darksky-card]

---

integration

Adds new integration [youdroid/home-assistant-sickchill]

---

integration

Adds new integration [garbled1/balboa_homeassistan]

---

integration

Adds new integration [garbled1/homeassistant_ecowitt]

---

theme

Adds new theme [DickSwart/swart_ninja_dark_theme]

---

plugin

Adds new plugin [pfunkmallone/HACS-camect-custom_card]

---

theme

https://github.com/Kibibit/hass-kibibit-theme

Adds new theme [kibibit/hass-kibibit-theme]

---

integration

wheel-custom-integrations PR: https://github.com/home-assistant/wheels-custom-integrations/pull/40
brands PR: https://github.com/home-assistant/brands/pull/1590
To the best of my knowledge those PRs bring it into compliance with the start guidance.

Adds new integration [eseglem/hass-wattbox]

---

integration

Adds new integration [briis/meteobridge]

---

integration

Adds new integration [nikrolls/homeassistant-goldair-climate]

---

integration

Adds new integration [briis/weatherbit]

---

integration

brands PR: https://github.com/home-assistant/brands/pull/1595

Adds new integration [eyalcha/read_your_meter]

---

plugin

Adds new plugin [dimagoltsman/generic-remote-control-card]

---

integration

Adds new integration [sockless-coding/panasonic_cc]

---

integration

Adds new integration [jeroenterheerdt/HAsmartirrigation]

---

integration

Adds new integration [sockless-coding/garo_wallbox]

---

integration

Adds new integration [youdroid/home-assistant-gitea]

---

appdaemon

Adds new appdaemon [simonhq/accu_allergies]

---

integration

All requirements are fulfilled as per the guide. See [issue tracking](https://github.com/nitobuendia/oura-custom-component/issues/1).

Adds new integration [nitobuendia/oura-custom-component]

---

integration

Adds new integration [Pyhive/HA-Hive-Custom-Component]

---

integration

Adds new integration [heyajohnny/cryptoinfo]

---

integration

Adds [GeorgeSG/ha-slack-user](https://github.com/GeorgeSG/ha-slack-user) integration.
- [home-assistant/wheels-custom-integrations PR](https://github.com/home-assistant/wheels-custom-integrations/pull/58)
- [home-assistant/brands PR](https://github.com/home-assistant/brands/pull/1630)

Adds new integration [GeorgeSG/ha-slack-user]

---

plugin

Adds new plugin [jeremywillans/lovelace-roomba-vacuum-card]

---

plugin

Adds new plugin [dimagoltsman/refreshable-picture-card]

---

integration

Adds new integration [vlumikero/home-assistant-securitas]

---

appdaemon

Adds new appdaemon [simonhq/snowydams]

---

integration

Adds new integration [laszlojakab/homeassistant-dijnet]

---

appdaemon

Adds new appdaemon [crserran/home-alarm]

---

integration

Adds new integration [mac-zhou/midea-ac-py]

---

.github/workflows/check-archived.yml
.github/workflows/check-brands.yml
.github/workflows/check-fork.yml
.github/workflows/check-hacs-manifest.yml
.github/workflows/check-hacs.yaml
.github/workflows/check-hassfest.yml
.github/workflows/check-images.yml
.github/workflows/check-info.yml
.github/workflows/check-manifest.yml
.github/workflows/check-owner.yml
.github/workflows/check-repository.yml
.github/workflows/check-wheels.yml
.github/workflows/lint-jq.yml

New trigger

---

plugin

this plugin is in symbiosis with the LG WebOS remote control

Adds new plugin [madmicio/channel-pad]

---

integration

Adds new integration [tellerbop/havistapool]

---

plugin

Adds new plugin [Villhellm/custom-sidebar]

---

appdaemon

Adds new appdaemon [hechi/GoodnightT]

---

plugin

Adds new plugin [iswitch/ha-yandex-icons]

---

appdaemon

Automatically control a room fan's speed based on a temperature sensor.
- [ x] You are submitting only 1 repository.
- [ x] You repository is compliant with https://hacs.xyz/docs/publish/start
- [ x] You have tested it with HACS by adding it as a custom repository.
- [ x] The list are still alphabetical after my change.

Adds new appdaemon [UbhiTS/ad-autofanspeed]

---

integration

Adds new integration [tikismoke/home-assistant-nespressoble]

---

integration

Adds new integration [finity69x2/nws_alerts]

---

plugin

Adds new plugin [artem-sedykh/mini-climate-card]

---

integration

Adds new integration [gjohansson-ST/sector]

---

integration

Other PR in HASS are on their way

Adds new integration [tikismoke/home-assistant-plcbus]

---

integration

Adds new integration [gilsonmandalogo/hacs-minerstat]

---

integration

Adds new integration [slesinger/HomeAssistant-PREdistribuce]

---

plugin

Custom lovelace card to use in Home assistant allowing you to redirect a user to certain view based on entity states.
- [X ] You are submitting only 1 repository.
- [X ] You repository is compliant with https://hacs.xyz/docs/publish/start
- [X ] You have tested it with HACS by adding it as a custom repository.
- [X ] The list are still alphabetical after my change.

Adds new plugin [ben8p/lovelace-tab-redirect-card]

---

appdaemon

Adds new appdaemon [haberda/tradfri_remotes]

---

theme

Adds new theme [3ative/3ative-blue-theme]

---

integration

Adds new integration [py-smart-gardena/hass-gardena-smart-system]

---

integration

Adds new integration [GuySie/ha-meural]

---

integration

Adds new integration [PiotrMachowski/Home-Assistant-custom-components-Saver]

---

integration

Adds new integration [ualex73/monitor_docker]

---

integration

Adds new integration [algirdasc/hass-floureon]

---

plugin

Adds new plugin [badguy99/PlantPictureCard]

---

integration

Adds new integration [jeroenterheerdt/HADailySensor]

---

integration

Adds new integration [asev/homeassistant-uponor]

---

.devcontainer/devcontainer.json
.github/workflows/checks.yml
Makefile
requirements.txt
scripts/check/owner.py

Use write access for owner check

---

plugin

Adds new plugin [DBa2016/power-usage-card-regex]

---

theme

Adds new theme [orickcorreia/caule-themes-pack-1]

---

integration

Adds new integration [ThermIQ/thermiq_mqtt-ha]

---

integration

Adds new integration [mrk-its/homeassistant-blitzortung]

---

theme

Added repo to theme defaults list

Adds new theme [awolkers/home-assistant-themes]

---

plugin

Adds new plugin [ironsheep/lovelace-lightning-detector-card]

---

plugin

Adds new plugin [rsnodgrass/water-heater-card]

---

integration

Adds new integration [nagyrobi/home-assistant-custom-components-linkplay]

---

plugin

Adds new plugin [thomasloven/lovelace-badge-card]

---

integration

Adds new integration [postlund/dlink_hnap]

---

scripts/is_sorted.py

Just in case anyone's confused why it isn't sorted, this PR helps you see the correct way to sort it.

Change is_sorted.py

---

appdaemon

Add Wasp in a Box AppDaemon app

Adds new appdaemon [wernerhp/appdaemon_wasp]

---

plugin

Adds new plugin [ironsheep/lovelace-rpi-monitor-card]

---

theme

This PR adds a lovelace dark soft UI theme.

Adds new theme [KTibow/lovelace-dark-soft-ui-theme]

---

plugin

Adds new plugin [Villhellm/lovelace-clock-card]

---

integration

Adds new integration [imicknl/ha-tahoma]

---

integration

Adds custom-components/pyscript to integration.

Adds new integration [custom-components/pyscript]

---

integration

Adds new integration [definitio/ha-rhvoice]

---

integration

Adds new integration [brefra/home-assistant-plugwise-stick]

---

theme

Adding a Home Assistant theme inspired on the iOS light mode interface.

Adds new theme [JuanMTech/ios_light_mode_theme]

---

integration

Adds new integration [jesserockz/ha-leafspy]

---

integration

Adds new integration [toreamun/amshan-homeassistant]

---

plugin

Adds new plugin [tomvanswam/compass-card]

---

integration

Adds new integration [FL550/dwd_weather]

---

plugin

Adds new plugin [finity69x2/cover-position-preset-row]

---

integration

Adds new integration [definitio/ha-sox]

---

plugin

Adding a Lovelace card that displays Norwegian mail delivery days.

Adds new plugin [ezand/lovelace-posten-card]

---

plugin

Adds a card I made to go fullscreen.

Adds new plugin [KTibow/fullscreen-card]

---

integration

Adds new integration [barban-dev/homeassistant-midea-dehumidifier]

---

plugin

This adds a custom scheduler card made by @nielsfaber which I am a major contributor to. (`@neliss` on the forums)

Adds new plugin [nielsfaber/scheduler-card]

---

integration

This adds a custom scheduler component made by @nielsfaber which I am a major contributor to. (`@neliss` on the forums)

Adds new integration [nielsfaber/scheduler-component]

---

integration

This PR adds an integration for the Hubitat Elevation hub.

Adds new integration [jason0x43/hacs-hubitat]

---

integration

Add new integration `phoenix_contact` (switch+services) for controlling Electric Vehicle Charge Control station by Phoenix Contact.

Adds new integration [mletenay/home-assistant-ev-charge-control]

---

plugin

Adds new plugin [fineemb/lovelace-colorfulclouds-weather-card]

---

integration

Adds new integration [alryaz/hass-pandora-cas]

---

plugin

https://github.com/Kibibit/kb-steam-card
thanks!

Adds new plugin [kibibit/kb-steam-card]

---

integration

Adds new integration [djtimca/haspacex]

---

integration

Adds new integration [hcoohb/hass-yeelightbt]

---

appdaemon

Adds new appdaemon [nickneos/Appdaemon-ZHA-Hue-Dimmer-Switch]

---

integration

@ludeeus this PR was previously filed and accepted in #592 but it got lost when my other integration PR in #604 was accepted.
I've just recreated this PR to get the integration added back again.

Adds new integration [swartjean/ha-eskom-loadshedding]

---

integration

Adds new integration [bremor/bonaire_myclimate]

---

appdaemon

Adds new appdaemon [nickneos/Appdaemon-ZHA-Xiaomi-Aqara-Switch]

---

integration

Adds new integration [mletenay/home-assistant-goodwe-inverter]

---

integration

adding current cost custom integration

Adds new integration [lolouk44/CurrentCost_HA_CC]

---

integration

Adds new integration [fineemb/xiaomi-cloud]

---

integration

Adds new integration [ayavilevich/homeassistant-dlink-presence]

---

integration

Adds new integration [turbulator/pandora-cas]

---

integration

Adds new integration [mvdwetering/huesyncbox]

---

integration

Adds new integration [joggs/home_assistant_ebeco]

---

plugin

Hey there 👋 ,
This PR adds my power-distribution-card to the HACS default repository.
It should fullfill all requirements. 
Thanks in advance!

Adds new plugin [jonahkr/power-distribution-card]

---

integration

…epositories
[lock-manager](https://github.com/FutureTense/lock-manager)

Adds new integration [futuretense/lock-manager]

---

netdaemon

Adds new netdaemon [LiranSX/NetDaemon-ITach-Wifi2IR]

---

integration

https://github.com/Danielhiversen/home_assistant_tractive
~~Waiting for: https://github.com/home-assistant/brands/pull/1884~~

Adds new integration [Danielhiversen/home_assistant_tractive]

---

integration

Adds new integration [kukulich/home-assistant-jablotron100]

---

integration

Adds new integration [troykelly/hacs-trackimo]

---

theme

Just adding @mikosoft83's theme. Planning to get some PRs merged in to it soon.

Adds new theme [mikosoft83/hass-windows10-themes]

---

plugin

Adds new plugin [turbulator/pandora-cas-card]

---

integration

Adds new integration [toreamun/victorsmartkill-homeassistant]

---

integration

Adds new integration [rt400/ReversoTTS-HA]

---

appdaemon

Adds new appdaemon [nickneos/Appdaemon-Ring-Doorbell-Automations]

---

plugin

Adds new plugin [matt8707/kiosk-mode]

---

integration

Adds new integration [fineemb/lynk-co]

---

integration

This is causing issue in the upcoming soon to be proposed https://hacs-sorted.web.app/

Remove duplicate jm-73/Indego integration

---

plugin

Please add this
[https://community.home-assistant.io/t/addon-input-number-with-and-buttons-to-replace-slider](https://community.home-assistant.io/t/addon-input-number-with-and-buttons-to-replace-slider)

Adds new plugin [htmltiger/numberbox-card]

---

.github/PULL_REQUEST_TEMPLATE.md

This points out the docs for publishing, and points out GitHub Actions.

Add HACS guidance

---

plugin

Adds new plugin [fineemb/lovelace-car-card]

---

plugin

Adds new plugin [TarheelGrad1998/gallery-card]

---

theme

Add Transparent Blue to HACS theme repo

Adds new theme [JOHLC/transparentblue]

---

theme

Adds new theme [einschmidt/github_dark_theme]

---

plugin

Added ciotlosm/lovelace-thermostat-dark-card plugin with new fixes on release.

Adds new plugin [ciotlosm/lovelace-thermostat-dark-card]

---

plugin

Adds new plugin [amaximus/transmission-card]

---

integration

Add Mail and Packages repo to default integrations

Adds new integration [moralmunky/Home-Assistant-Mail-And-Packages]

---

integration

Adds new integration [AlexxIT/SonoffLAN]

---

blacklist
integration
removed

NWS removed the server for radar images breaking this integration.

Remove MatthewFlamm/nwsradar

---

.github/workflows/checks.yml
blacklist
integration
removed
scripts/changed/repo.py

Remove custom-components/uilogs

---

integration

Adding this instead of https://github.com/hacs/default/pull/766

Adds new integration [bosch-thermostat/home-assistant-bosch-custom-component]

---

plugin

Adds new plugin [IhorSyerkov/linak-desk-card]

---

plugin

[idittansikte/bootstrap-grid-card](https://github.com/idittansikte/bootstrap-grid-card)

Adds new plugin [idittansikte/bootstrap-grid-card]

---

blacklist
plugin
removed

I plan to archive this repo as this functionality is already in lovelace core.

Remove bratanon/lovelace-conditional-entity-row

---

plugin

[grinstantin/todoist-card](https://github.com/grinstantin/todoist-card)

Adds new plugin [grinstantin/todoist-card]

---

integration

Adds new integration [mawinkler/astroweather]

---

integration

Adds new integration [erikkastelec/hass-WEM-Portal]

---

.github/workflows/checks.yml
scripts/check/edits.py

Add edits check

---

theme

I would not even dare to call it a theme 😃 
Nevertheless, adding it 👍

Adds new theme [frenck/home-assistant-theme-outline]

---

plugin

Adds new plugin [finity69x2/fan-percent-button-row]

---

integration

Adds new integration [bieniu/ha-zadnego-ale]

---

integration

Adds new integration [AlexxIT/YandexStation]

---

integration

Adds new integration [viktak/ha-cc-abalin-nameday]

---

integration

Adds new integration [koying/jellyfin_ha]

---

plugin

Adds new plugin [finity69x2/fan-mode-button-row]

---

integration

Adds new integration [Petro31/ha-integration-multizone-controller]

---

integration

Adds new integration [bramstroker/homeassistant-powercalc]

---

plugin

Adds new plugin [rianadon/timer-bar-card](https://github.com/rianadon/timer-bar-card)

Adds new plugin [rianadon/timer-bar-card]

---

integration

I [previously](https://github.com/hacs/default/pull/773) requested this merge, but didn't have the time to fix the issues.
I added GitHub actions to validate my repo according to https://hacs.xyz/docs/publish/action/ and https://github.com/home-assistant/actions - everything should be passing now.

Adds new integration [GuyLewin/home-assistant-crunch-o-meter]

---

integration

Adds new integration [CJNE/ha-sunspec]

---

integration

Adds new integration [firstof9/ha-openei]

---

integration

Adds new integration [golles/ha-kamstrup_403]

---

integration

Adds new integration [eifinger/hass-here-weather]

---

plugin

Adds new plugin [pmongloid/flipdown-timer-card]

---

integration

Added Kia UVO / Hyundai Bluelink Integration @fuatakgun

Adds new integration [fuatakgun/kia_uvo]

---

integration

Adds new integration [viragelabs/virage_dashboard]

---

integration

Adds new integration [KartoffelToby/ai_thermostat]

---

plugin

https://community.home-assistant.io/t/addon-lovelace-configuration-yaml-editor-for-core-install/362093

Adds new plugin [htmltiger/config-editor-card]

---

blacklist
integration
removed

removing briis/smartweather

---

integration

Adds new integration [spycle/microbot_push]

---

integration

Adding the Peloton Integration from https://github.com/edwork/homeassistant-peloton-sensor

Adds new integration [edwork/homeassistant-peloton-sensor]

---

theme

Adds a new theme that is basically the other two combined and re-coded. (Feel free to remove the other two from defaults if you want.)

Adds new theme [KTibow/lovelace-soft-theme]

---

integration

Adding custom integration for Thermia heat pumps.
HACS and HA workflow checks in repo have passed.

Adds new integration [klejejs/ha-thermia-heat-pump-integration]

---

integration

Adds new integration [jugla/keyatome]

---

integration

Revert "Adds new integration [9a4gl/hass-centrometal-boiler]"

---

blacklist
integration
removed

Replaces https://github.com/hacs/default/pull/1205

Remove sdebruyn/homeassistant-bpost-integration

---

plugin

This is the official icon pack for the [Thermal Comfort](https://github.com/dolezsa/thermal_comfort) custom integrations.

Adds new plugin [rautesamtr/thermal_comfort_icons]

---

blacklist
integration
removed

Remove archived Omnik Solar integration

---

integration

Hi !
This is for a new integration for Gogs platform, self-hosted Git service.
This is my PR for brands ; https://github.com/home-assistant/brands/pull/3126

Adds new integration [youdroid/home-assistant-gogs]

---

netdaemon

Added the repo "ElVit/netdaemon-notify-on-update"

Adds new netdaemon [ElVit/netdaemon-notify-on-update]

---

integration

Adds new integration [thecode/ha-rpi_gpio]

---

plugin

A new collection of lovelace cards : [Mushroom Cards](https://github.com/piitaya/lovelace-mushroom)

Adds new plugin [piitaya/lovelace-mushroom]

---

integration

Adds new integration [sakowicz/home-assistant-tenda-tracker]

---

plugin

Adds new plugin [frozenwizard/onlylocklock]

---

integration

Adds new integration [evilmarty/mjpeg-timelapse]

---

blacklist
integration
removed

Closes https://github.com/hacs/integration/issues/2517

Remove rgruebel/ha_zigbee2mqtt_networkmap

---

integration

Adds new integration [amaximus/fire_protection_hu]

---

plugin

Adds new plugin [gadgetchnnel/lovelace-header-cards]

---

integration

Adds new integration [dahlb/ha_hatch]

---

integration

Adds new theme [flejz/hass-cyberpunk-2077-theme]

---

integration

Adds new integration [GuyLewin/home-assistant-lifetime-fitness]

---

integration

Adds new integration [toringer/home-assistant-sbanken]

---

integration

Adds new integration [patrickribbing/sjofartsverket_viva-component]

---

integration

Adds new integration [kongo09/hass-dell-printer]

---

integration

Adds new integration [NickM-27/swatch-hass-integration]

---

plugin

Adds new plugin [Kaptensanders/skolmat-card]

---

integration

**Link to successful HACS action:**  https://github.com/snikch/climate.escea/actions/runs/2375370342
**Link to successful hassfest action (if integration):**  https://github.com/snikch/climate.escea/actions/runs/2375370340

Adds new integration [snikch/climate.escea]

---

integration

https://github.com/elahd/ha-cyclepay
**Link to successful HACS action:**  https://github.com/elahd/ha-cyclepay/runs/6970568613
**Link to successful hassfest action (if integration):**  https://github.com/elahd/ha-cyclepay/runs/6970568613 (Both run in same workflow.)

Adds new integration [elahd/ha-cyclepay]

---

integration

**Link to successful HACS action:**  https://github.com/godely/ha-dremel-3d-printer/runs/6996255171?check_suite_focus=true
**Link to successful hassfest action (if integration):**  https://github.com/godely/ha-dremel-3d-printer/runs/6996255171?check_suite_focus=true

Adds new integration [godely/ha-dremel-3d-printer]

---

integration

**Link to successful HACS action: https://github.com/georgezhao2010/fordpass_china/actions/runs/2603406671
**Link to successful hassfest action (if integration): https://github.com/georgezhao2010/fordpass_china/actions/runs/2603406671

Adds new integration [georgezhao2010/fordpass_china]

---

plugin

**Link to successful HACS action: https://github.com/georgezhao2010/lovelace-curtain-card/actions/runs/2603357859
**Link to successful hassfest action (if integration): N/A

Adds new plugin [georgezhao2010/lovelace-curtain-card]

---

integration

https://github.com/infradom/ecopower_dynamic_grid_prices/actions/runs/2605712027
https://github.com/infradom/ecopower_dynamic_grid_prices/actions/runs/2605712026

Adds new integration [infradom/ecopower_dynamic_grid_prices]

---

integration

Link to successful HACS action: https://github.com/henricm/ha-ferroamp/actions/runs/2816940946
Link to successful hassfest action (if integration): https://github.com/henricm/ha-ferroamp/actions/runs/2816940959

Adds new integration [henricm/ha-ferroamp]

---

integration

**Link to successful HACS action:**  https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/runs/8054825368
**Link to successful hassfest action (if integration):**  https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/runs/8054825368

Adds new integration [BottlecapDave/HomeAssistant-OctopusEnergy]

---

integration

**Link to successful HACS action:**  https://github.com/BottlecapDave/HomeAssistant-FirstBus/runs/8055894103
**Link to successful hassfest action (if integration):**  https://github.com/BottlecapDave/HomeAssistant-FirstBus/runs/8055894103

Adds new integration [BottlecapDave/HomeAssistant-FirstBus]

---

integration

**Link to successful HACS action:**  https://github.com/amitfin/daily_schedule/runs/7808089153
**Link to successful hassfest action (if integration):**  https://github.com/amitfin/daily_schedule/runs/7808089153

Adds new integration [amitfin/daily_schedule]

---

plugin

**Link to successful HACS action:**  https://github.com/berrywhite96/lovelace-shutter-row/runs/8102020710?check_suite_focus=true

Adds new plugin [berrywhite96/lovelace-shutter-row]

---

integration

**Link to successful HACS action:**  https://github.com/FaserF/ha-deutschebahn/runs/8265136593
**Link to successful hassfest action (if integration):**  https://github.com/FaserF/ha-deutschebahn/runs/8265136593

Adds new integration [faserf/ha-deutschebahn]

---

integration

**Link to successful HACS action: https://github.com/DeerMaximum/QR-Code-Generator/actions/runs/3038502495/jobs/4892284863**
**Link to successful hassfest action (if integration): https://github.com/DeerMaximum/QR-Code-Generator/actions/runs/3038502495/jobs/4892284863**

Adds new integration [DeerMaximum/QR-Code-Generator]

---

integration

**Link to successful HACS action:**  https://github.com/Vaskivskyi/ha-chroma/actions/runs/3044433113/jobs/4911056705
**Link to successful hassfest action (if integration):** https://github.com/Vaskivskyi/ha-chroma/actions/runs/3044433113/jobs/4911056599

Adds new integration [Vaskivskyi/ha-chroma]

---

integration

Adds new integration [lorenzo-deluca/homeassistant-silence]

---

integration

https://github.com/monty68/uniled/actions/runs/3782710223
**Link to successful hassfest action (if integration):**  
https://github.com/monty68/uniled/actions/runs/3782710222

Adds new integration [monty68/uniled]

---

plugin

Adds new plugin [iablon/HomeAssistant-Touchpad-Card]

---

integration

**Link to successful HACS action:**  https://github.com/BobTheShoplifter/HomeAssistant-Posten/actions/runs/3791140505
**Link to successful hassfest action (if integration):**  https://github.com/BobTheShoplifter/HomeAssistant-Posten/actions/runs/3791140504

Adds new integration [BobTheShoplifter/HomeAssistant-Posten]

---

integration

**Link to successful HACS action:**
https://github.com/CM000n/qss/actions/runs/3786242490/jobs/6436961896
**Link to successful hassfest action (if integration):**  
https://github.com/CM000n/qss/actions/runs/3786242490/jobs/6436962005

Adds new integration [CM000n/qss]

---

blacklist
integration
removed
scripts/remove_publishers.py

Closes https://github.com/hacs/integration/issues/2986

Remove author Kraineff

---

blacklist
plugin
removed

A PR was opened to correct it over 6 months ago, time to remove it.
ref: https://github.com/ljmerza/reddit-card/pull/8
related to https://github.com/ljmerza/reddit-card/issues/10

Remove ljmerza/reddit-card

---

integration

**Link to successful HACS action:** https://github.com/hg1337/homeassistant-dwd/actions/runs/3832311425 
**Link to successful hassfest action (if integration):** https://github.com/hg1337/homeassistant-dwd/actions/runs/3832311422

Adds new integration [hg1337/homeassistant-dwd]

---

template

:)
Link to current release: <https://github.com/TheFes/relative-time-plus/releases/tag/v0.2.2>
Link to successful HACS action (without the `ignore` key): <https://github.com/TheFes/relative-time-plus/actions/runs/4628745129>

Adds new template [TheFes/relative-time-plus]

---

template

Adds entity_id based time calculations macros.
Link to current release: <https://github.com/Petro31/easy-time-jinja/tree/v1.0.2>
Link to successful HACS action (without the `ignore` key): <https://github.com/Petro31/easy-time-jinja/actions/runs/4640008600>

Adds new template [Petro31/easy-time-jinja]

---

blacklist
integration
removed

Link to current release: <>
Link to successful HACS action (without the `ignore` key): <>

Remove peternijssen/home-assistant-jumbo

---

blacklist
integration
removed

Remove geertmeersman/telenet

---

blacklist
integration
removed

Link to current release: <>
Link to successful HACS action (without the `ignore` key): <>

Remove toringer/home-assistant-sbanken

---

blacklist
integration
removed

Closes https://github.com/hacs/integration/issues/3500
Link to current release: <>
Link to successful HACS action (without the `ignore` key): <>

Remove mauro-midolo/homeassistant_electrolux_status

---

.github/workflows/lint.yml
.github/workflows/upload-critical.yml
.github/workflows/upload-removed.yml
tools/jsonschema/critical.schema.json
tools/jsonschema/removed.schema.json
tools/jsonschema/repositories.schema.json

Adjust actions to include JSON schema validation

Add JSON schema validation

---

blacklist
integration
removed

Closes https://github.com/hacs/integration/issues/4023

Remove websylv/homeassistant-meteoswiss

---

blacklist
plugin
removed

Closes https://github.com/hacs/integration/issues/4019

Remove marcokreeft87/room-card

---

blacklist
integration
removed

Closes https://github.com/hacs/integration/issues/4031

Remove nagyrobi/home-assistant-custom-components-linkplay

---

integration

Link to current release: https://github.com/krasnoukhov/homeassistant-nova-poshta/releases/tag/v1.1.0
Link to successful HACS action (without the `ignore` key): https://github.com/krasnoukhov/homeassistant-nova-poshta/actions/runs/7699204549/job/20980267826
Link to successful hassfest action (if integration): https://github.com/krasnoukhov/homeassistant-nova-poshta/actions/runs/7699204555/job/20980267846

Adds new integration [krasnoukhov/homeassistant-nova-poshta]

---

integration

Link to current release: https://github.com/krasnoukhov/homeassistant-tesy/releases/tag/v1.1.0
Link to successful HACS action (without the `ignore` key): https://github.com/krasnoukhov/homeassistant-tesy/actions/runs/7698963212/job/20979488969
Link to successful hassfest action (if integration): https://github.com/krasnoukhov/homeassistant-tesy/actions/runs/7698963200/job/20979488990

Adds new integration [krasnoukhov/homeassistant-tesy]

---

appdaemon
blacklist
integration
plugin
removed

Remove archived repositories

---

integration

Link to current release: <https://github.com/faizpuru/ha-ambeo_soundbar/releases/tag/1.0.0>
Link to successful HACS action (without the `ignore` key): <https://github.com/faizpuru/ha-ambeo_soundbar/actions/runs/8173841543/job/22347192600>
Link to successful hassfest action (if integration): <https://github.com/faizpuru/ha-ambeo_soundbar/actions/runs/8173841541/job/22347192253>

Adds new integration [faizpuru/ha-ambeo_soundbar]

---

blacklist
integration
removed

Replaces #2468 
Closes https://github.com/hacs/integration/issues/3661

Remove myTselection/MijnTuin

---

blacklist
integration
removed

Closes https://github.com/hacs/integration/issues/4382

Remove MesserschmittX/ha-nicehash-excavator-monitor

---

blacklist
integration
removed

Closes https://github.com/hacs/integration/issues/3748

Remove georgezhao2010/midea_ac_lan

---

blacklist
integration
removed

Closes https://github.com/hacs/integration/issues/4391

Remove FaserF/ha-deutschebahn

---

blacklist
integration
removed

Closes https://github.com/hacs/integration/issues/4317

Remove dreed47/redfin

---

.github/workflows/upload-critical.yml
.github/workflows/upload-removed.yml

Pin AWS CLI to 1.36.39

---

blacklist
integration
removed

Closes https://github.com/hacs/integration/issues/4254

Remove rogsme/ute_homeassistant_integration

---

blacklist
integration
removed

Remove FaserF/ha-rewe

---

blacklist
integration
plugin
removed

Closes https://github.com/hacs/integration/issues/4418
Closes https://github.com/hacs/integration/issues/4419

Remove krisinfo

---

integration

Link to current release: <https://github.com/mukaschultze/ha-must-inverter/releases/tag/v0.1.6>
Link to successful HACS action (without the `ignore` key): <https://github.com/mukaschultze/ha-must-inverter/actions/runs/7550783613>
Link to successful hassfest action (if integration): <https://github.com/mukaschultze/ha-must-inverter/actions/runs/7550783613>

Adds new integration [mukaschultze/ha-must-inverter]

---

integration

Link to current release: <https://github.com/avishorp/sync_group/releases/tag/v0.1.0>
Link to successful HACS action (without the `ignore` key): <https://github.com/avishorp/sync_group/actions/runs/9437761008>
Link to successful hassfest action (if integration): <https://github.com/avishorp/sync_group/actions/runs/9437761017>

Adds new integration [avishorp/sync_group]

---

integration

Link to current release: <https://github.com/chris-mc1/homeconnect_local_hass/releases/tag/1.0.1>
Link to successful HACS action (without the `ignore` key): <https://github.com/chris-mc1/homeconnect_local_hass/actions/runs/14065344582/job/39386272842>
Link to successful hassfest action (if integration): <https://github.com/chris-mc1/homeconnect_local_hass/actions/runs/14065344582/job/39386274003>

Adds new integration [chris-mc1/homeconnect_local_hass]

---

integration

Link to current release: https://github.com/elboletaire/ha-weatherxm/releases/tag/1.2.0
Link to successful HACS action (without the `ignore` key): https://github.com/elboletaire/ha-weatherxm/actions/runs/14269235407/job/39998374561
Link to successful hassfest action (if integration): https://github.com/elboletaire/ha-weatherxm/actions/runs/14269235407/job/39998374568

Adds new integration [elboletaire/ha-weatherxm]

---

integration

Link to current release: <https://github.com/raelix/HA-Radoff-integration/releases/tag/0.2.0>
Link to successful HACS action (without the `ignore` key): <https://github.com/raelix/HA-Radoff-integration/actions/runs/12332540842/job/34420481946>
Link to successful hassfest action (if integration): <https://github.com/raelix/HA-Radoff-integration/actions/runs/12332540842/job/34420482016>

Adds new integration [raelix/HA-Radoff-integration]

---

integration

Link to current release: https://github.com/barreeeiroo/Home-Assistant-Electric-Ireland/releases/tag/v0.1.1
Link to successful HACS action (without the `ignore` key): https://github.com/barreeeiroo/Home-Assistant-Electric-Ireland/actions/runs/13082015630/job/36775786607
Link to successful hassfest action (if integration): https://github.com/barreeeiroo/Home-Assistant-Electric-Ireland/actions/runs/13082015630/job/36775786607

Adds new integration [barreeeiroo/Home-Assistant-Electric-Ireland]

---

integration

Link to current release: <https://github.com/kgn3400/docker_status/releases/tag/v1.0.15>
Link to successful HACS action (without the `ignore` key): <https://github.com/kgn3400/docker_status/actions/runs/12849075028>
Link to successful hassfest action (if integration): <https://github.com/kgn3400/docker_status/actions/runs/12849241292>

Adds new integration [kgn3400/docker_status]

---

integration

Link to current release: <https://github.com/kgn3400/hiper_drift/releases/tag/v1.0.25>
Link to successful HACS action (without the `ignore` key): <https://github.com/kgn3400/hiper_drift/actions/runs/11788631438>
Link to successful hassfest action (if integration): <https://github.com/kgn3400/hiper_drift/actions/runs/11788992263>

Adds new integration [kgn3400/hiper_drift]

---

integration

Link to current release: [v0.1.28](https://github.com/Makr91/ha_easgen/releases/tag/v0.1.28)
Link to successful HACS action (without the `ignore` key): [HACS Action](https://github.com/Makr91/ha_easgen/actions/runs/15463754380/job/43530910659)
Link to successful hassfest action (if integration): [hassfest Action](https://github.com/Makr91/ha_easgen/actions/runs/15463754380/job/43530910675)

Adds new integration [Makr91/ha_easgen]

---

plugin

Link to current release: https://github.com/nutteloost/actions-card/releases/tag/v1.2.0
Link to successful HACS action (without the `ignore` key): https://github.com/nutteloost/actions-card/actions/runs/15487738998

Adds new plugin [nutteloost/actions-card]

---

integration

This adds the integration for Elegoo's 3d Printers
Link to current release: <https://github.com/danielcherubini/elegoo-homeassistant/releases/tag/v0.8.4>
Link to successful HACS action (without the `ignore` key): <https://github.com/danielcherubini/elegoo-homeassistant/actions/runs/15495863342/job/43632318359>
Link to successful hassfest action (if integration): <https://github.com/danielcherubini/elegoo-homeassistant/actions/runs/15495863342/job/43632318354>

Adds new integration [danielcherubini/elegoo-homeassistant]

---

integration

Link to current release: https://github.com/Lewa-Reka/ha-rce-pse/releases/tag/0.4.0
Link to successful HACS action (without the `ignore` key): https://github.com/Lewa-Reka/ha-rce-pse/actions/runs/15505149871/job/43658976330
Link to successful hassfest action (if integration): https://github.com/Lewa-Reka/ha-rce-pse/actions/runs/15505149871/job/43658976327

Adds new integration [Lewa-Reka/ha-rce-pse]

---

integration

Link to current release: https://github.com/svasek/homeassistant-vistapool-modbus/releases/tag/v1.2.4
Link to successful HACS action (without the `ignore` key): https://github.com/svasek/homeassistant-vistapool-modbus/actions/runs/15492546261
Link to successful hassfest action (if integration): https://github.com/svasek/homeassistant-vistapool-modbus/actions/runs/15492546274

Adds new integration [svasek/homeassistant-vistapool-modbus]

---

plugin

Link to current release: https://github.com/prl159/custom-todo/releases/tag/v4.0.2
Link to successful HACS action (without the `ignore` key): https://github.com/prl159/custom-todo/actions/runs/15303667417/job/43050686377

Adds new plugin [prl159/custom-todo]

---

integration

Link to current release: [<>](https://github.com/wbyoung/movement/releases/tag/v0.1.1)
Link to successful HACS action (without the `ignore` key): [<>](https://github.com/wbyoung/movement/actions/runs/15567492701/job/43835022123)
Link to successful hassfest action (if integration): [<>](https://github.com/wbyoung/movement/actions/runs/15567492701/job/43835022101)

Adds new integration [wbyoung/movement]

---

integration

Link to current release: [<>](https://github.com/tube0013/Smartcar-HA/releases/tag/v0.3.1)
Link to successful HACS action (without the `ignore` key): [<>](https://github.com/tube0013/Smartcar-HA/actions/runs/15547438889/job/43771562501)
Link to successful hassfest action (if integration): [<>](https://github.com/tube0013/Smartcar-HA/actions/runs/15547438889/job/43771562502)

Adds new integration [tube0013/Smartcar-HA]

---

integration

Adds the parcel-ha integration. This is maintained by jmdevita and PineappleEmperor.
Link to current release: https://github.com/jmdevita/parcel-ha/releases/tag/v1.5.2
Link to successful HACS action (without the `ignore` key): https://github.com/jmdevita/parcel-ha/actions/runs/15598313112
Link to successful hassfest action (if integration): https://github.com/jmdevita/parcel-ha/actions/runs/15573106531

Adds new integration [jmdevita/parcel-ha]

---

integration

Link to current release: https://github.com/alryaz/hass-mosoblgaz/releases/tag/v2025.6.3
Link to successful HACS action (without the `ignore` key): https://github.com/alryaz/hass-mosoblgaz/actions/runs/15657819411
Link to successful hassfest action (if integration): https://github.com/alryaz/hass-mosoblgaz/actions/runs/15657819409

Adds new integration [alryaz/hass-mosoblgaz]

---

integration

Link to current release: https://github.com/Haluska77/regulus-ha/releases/tag/1.0.0
Link to successful HACS action (without the ignore key): https://github.com/Haluska77/regulus-ha/actions
Link to successful hassfest action (if integration): https://github.com/Haluska77/regulus-ha/actions/workflows/hassfest.yml

Adds new integration [Haluska77/regulus-ha]

---

integration

Link to current release: <https://github.com/kcsoft/virtual-keys/releases/tag/v1.0.0>
Link to successful HACS action (without the `ignore` key): <https://github.com/kcsoft/virtual-keys/actions/runs/15700793775>
Link to successful hassfest action (if integration): <https://github.com/kcsoft/virtual-keys/actions/runs/15700793821>

Adds new integration [kcsoft/virtual-keys]

---

integration

Link to current release: https://github.com/svante-jacobsen/loggamera-home-assistant/releases/tag/v1.0.2
Link to successful HACS action (without the `ignore` key): https://github.com/svante-jacobsen/loggamera-home-assistant/actions/runs/15706473323
Link to successful hassfest action (if integration): https://github.com/svante-jacobsen/loggamera-home-assistant/actions/runs/15706473323

Adds new integration [svante-jacobsen/loggamera-home-assistant]

---

blacklist
plugin
removed

Closes https://github.com/hacs/integration/issues/4172

Remove custom-cards/bar-card

---

blacklist
plugin
removed

Closes https://github.com/hacs/integration/issues/4199

Remove Deejayfool/hass-shutter-card

---

blacklist
integration
removed

Closes https://github.com/hacs/integration/issues/4208

Remove tetienne/veolia-custom-component

---

integration

Link to current release: <https://github.com/Master13011/vacances-scolaire-HA/releases/tag/2.1.1 >
Link to successful HACS action (without the `ignore` key): <https://github.com/Master13011/vacances-scolaire-HA/actions/runs/15970523118/job/45040499331>
Link to successful hassfest action (if integration): <https://github.com/Master13011/vacances-scolaire-HA/actions/runs/15970523112/job/45040499348>

Adds new integration [Master13011/vacances-scolaire-HA]

---

integration

Link to current release: <https://github.com/dhover/ha-iungo/releases/tag/1.1.8>
Link to successful HACS action (without the `ignore` key): <https://github.com/dhover/ha-iungo/actions/runs/16002999776>
Link to successful hassfest action (if integration): <https://github.com/dhover/ha-iungo/actions/runs/16002999745>

Adds new integration [dhover/ha-iungo]

---

integration

Link to current release: https://github.com/ddrimus/ha-tper-tracker/releases/tag/v1.0.0
Link to successful HACS action (without the `ignore` key): https://github.com/ddrimus/ha-tper-tracker/actions/runs/16037243198
Link to successful hassfest action (if integration): https://github.com/ddrimus/ha-tper-tracker/actions/runs/16037243202

Adds new integration [ddrimus/ha-tper-tracker]

---

integration

Link to current release: <https://github.com/moehrem/DiveraControl/releases/tag/v1.1-update>
Link to successful HACS action (without the `ignore` key): <https://github.com/moehrem/DiveraControl/actions/runs/16022912313/job/45203887276>
Link to successful hassfest action (if integration): <https://github.com/moehrem/DiveraControl/actions/runs/16022912317/job/45203887245>
Thank you for your work!

Adds new integration [moehrem/DiveraControl]

---

integration

Link to current release: <https://github.com/Dams51/Pleinchamp/releases/tag/v0.1.4>
Link to successful HACS action (without the `ignore` key): <https://github.com/Dams51/Pleinchamp/actions/runs/16039766499>
Link to successful hassfest action (if integration): <https://github.com/Dams51/Pleinchamp/actions/runs/16039045614>

Adds new integration [Dams51/Pleinchamp]

---

plugin

Link to current release: https://github.com/cataseven/Switch-and-Timer-Bar-Card/releases/tag/v1.0.1
Link to successful HACS action (without the `ignore` key): https://github.com/cataseven/Switch-and-Timer-Bar-Card/actions/runs/16060935662

Adds new plugin [cataseven/Switch-and-Timer-Bar-Card]

---

integration

Link to current release: <https://github.com/HarvsG/ha-glinet4-integration/releases/tag/v0.1.1>
Link to successful HACS action (without the `ignore` key): <https://github.com/HarvsG/ha-glinet4-integration/actions/runs/16080348374/job/45383918597>
Link to successful hassfest action (if integration): <https://github.com/HarvsG/ha-glinet4-integration/actions/runs/16080348381/job/45383918620>

Adds new integration [HarvsG/ha-glinet4-integration]

---

integration

Link to current release: https://github.com/Tom-Bom-badil/home-assistant_ugreen-nas/releases/tag/v2025-07.1
Link to successful HACS action (without the `ignore` key): https://github.com/Tom-Bom-badil/home-assistant_ugreen-nas/actions/runs/16101003308  _(comment: HA brand was just added today, that was the single error that let it fail all the days before)_
Link to successful hassfest action (if integration): https://github.com/Tom-Bom-badil/home-assistant_ugreen-nas/actions/runs/16101003313

Adds new integration [Tom-Bom-badil/home-assistant_ugreen-nas]

---

blacklist
plugin
removed

Remove archived repository berrywhite96/lovelace-shutter-row

---

integration

Link to current release: <https://github.com/starwarsfan/shadow-control/releases>
Link to successful HACS action (without the `ignore` key): <https://github.com/starwarsfan/shadow-control/actions/runs/16157357751/job/45602459088>
Link to successful hassfest action (if integration): <https://github.com/starwarsfan/shadow-control/actions/runs/16157357751/job/45602459087>

Adds new integration [starwarsfan/shadow-control]

---

blacklist
integration
removed

Remove deleted repository infradom/ecopower_dynamic_grid_prices

---

plugin

Link to current release: https://github.com/unbekannt3/room-card-minimalist/releases/tag/v1.0.0
Link to successful HACS action (without the `ignore` key): https://github.com/unbekannt3/room-card-minimalist/actions/runs/16351054324

Adds new plugin [unbekannt3/room-card-minimalist]

---

python_script

Link to current release: <https://github.com/kapkirk/Indice-di-qualita-dell-aria-via-Home-Assistant>
Link to successful HACS action (without the `ignore` key): <https://github.com/kapkirk/Indice-di-qualita-dell-aria-via-Home-Assistant/actions/runs/16496532088/job/46643512258>

Adds new python_script [kapkirk/Indice-di-qualita-dell-aria-via-Home-Assistant]

---

integration

Link to current release: <https://github.com/Domintell/ha_domintell/releases/tag/v0.4.12>
Link to successful HACS action (without the `ignore` key): <https://github.com/Domintell/ha_domintell/actions/runs/14971292229/job/42052610528>
Link to successful hassfest action (if integration): <https://github.com/Domintell/ha_domintell/actions/runs/14971292229/job/42052610518>

Adds new integration [Domintell/ha_domintell]

---

plugin

Link to current release: <https://github.com/sierramike/lovelace-simple-navbar/releases/tag/v1.0.1>
Link to successful HACS action (without the `ignore` key): <https://github.com/sierramike/lovelace-simple-navbar/actions/runs/16545679272>

Adds new plugin [sierramike/lovelace-simple-navbar]

---

integration

Link to current release: <> https://github.com/myny-git/smappee_ev/releases/tag/2025.7.10
Link to successful HACS action (without the ignore key): <> https://github.com/myny-git/smappee_ev/actions/runs/16552877443
Link to successful hassfest action (if integration): <> https://github.com/myny-git/smappee_ev/actions/runs/16552877444

Adds new integration [myny-git/smappee_ev]

---

blacklist
integration
removed

Remove cnecrea/infpro

---

integration

Link to current release: https://github.com/Zendure/Zendure-HA/releases/tag/1.0.47
Link to successful HACS action (without the `ignore` key): https://github.com/Zendure/Zendure-HA/actions/runs/16661064507/job/47158101181
Link to successful hassfest action (if integration): https://github.com/Zendure/Zendure-HA/actions/runs/16661064513/job/47158101253

Adds new integration [Zendure/Zendure-HA]

---

plugin

Link to current release: https://github.com/timmaurice/lovelace-background-graph-entities/releases/tag/1.0.0
Link to successful HACS action (without the `ignore` key): https://github.com/timmaurice/lovelace-background-graph-entities/actions/runs/16759112246

Adds new plugin [timmaurice/lovelace-background-graph-entities]

---

integration

Link to current release: <https://github.com/brewmarsh/meraki-homeassistant/releases/tag/v1.4.0>
Link to successful HACS action (without the `ignore` key): <https://github.com/brewmarsh/meraki-homeassistant/actions/runs/16975170735/job/48122137625>
Link to successful hassfest action (if integration): <https://github.com/brewmarsh/meraki-homeassistant/actions/runs/16975166866/job/48122122306>

Adds new integration [brewmarsh/meraki-homeassistant]

---

plugin

Link to current release: https://github.com/timmaurice/lovelace-rss-accordion/releases/tag/0.0.1
Link to successful HACS action (without the `ignore` key): https://github.com/timmaurice/lovelace-rss-accordion/actions/runs/17049973402/job/48334973788

Adds new plugin [timmaurice/lovelace-rss-accordion]

---

plugin

Link to current release: https://github.com/timmaurice/lovelace-radar-card/releases/tag/0.0.1
Link to successful HACS action (without the `ignore` key): https://github.com/timmaurice/lovelace-radar-card/actions/runs/17102995629

Adds new plugin [timmaurice/lovelace-radar-card]

---

blacklist
integration
removed

Remove msinhore/adaptive_climate

---

blacklist
integration
removed

Closes https://github.com/hacs/integration/issues/4439

Remove msp1974/homeassistant-jlrincontrol

---

integration

Thanks for your hard work, kind maintainer!
Link to current release: https://github.com/bharat/homeassistant-triad-ams/releases/tag/v2025.9.15
Link to successful HACS action (without the `ignore` key): [<>](https://github.com/bharat/homeassistant-triad-ams/actions/runs/17722705375/job/50357802227)
Link to successful hassfest action (if integration): https://github.com/bharat/homeassistant-triad-ams/actions/runs/17722705375/job/50357802231

Adds new integration [bharat/homeassistant-triad-ams]

---

blacklist
plugin
removed

Closes https://github.com/hacs/integration/issues/4453

Remove nervetattoo/simple-thermostat

---

integration

Link to current release: <https://github.com/remmob/sht20/releases/tag/v1.0.1>
Link to successful HACS action (without the `ignore` key): <https://github.com/remmob/sht20/actions/runs/17783455826>
Link to successful hassfest action (if integration): <https://github.com/remmob/sht20/actions/runs/17784065671>

Adds new integration [remmob/sht20]

---

blacklist
integration
removed

Remove eifinger/hass-here-weather

---

integration

Link to current release: https://github.com/ThomasHFWright/kippy-homeassistant/releases/tag/v1.0.1
Link to successful HACS action (without the `ignore` key): https://github.com/ThomasHFWright/kippy-homeassistant/actions/runs/17946729235
Link to successful hassfest action (if integration): https://github.com/ThomasHFWright/kippy-homeassistant/actions/runs/17946729238

Adds new integration [ThomasHFWright/kippy-homeassistant]

---

integration

Link to current release: <https://github.com/aLAN-LDZ/ThesslaGreen_HA/releases/tag/0.2.2>
Link to successful HACS action (without the `ignore` key): <https://github.com/aLAN-LDZ/ThesslaGreen_HA/actions/runs/17984585829>
Link to successful hassfest action (if integration): <https://github.com/aLAN-LDZ/ThesslaGreen_HA/actions/runs/17984545940>

Adds new integration [aLAN-LDZ/ThesslaGreen_HA]

---

blacklist
integration
removed

Closes https://github.com/hacs/integration/issues/4519

Remove asev/homeassistant-uponor

---

blacklist
integration
removed

Closes https://github.com/hacs/integration/issues/4578

Remove modrzew/hass-flashforge-adventurer-3

---

integration
plugin

- [X ] I've created a new release of the repository after the validation actions were run successfully.
Link to current release: <https://github.com/0xAHA/Midea-Heat-Pump-HA/releases/tag/v0.2.3>
Link to successful HACS action (without the `ignore` key): <https://github.com/0xAHA/Midea-Heat-Pump-HA/actions/runs/17890571060>
Link to successful hassfest action (if integration): <https://github.com/0xAHA/Midea-Heat-Pump-HA/actions/runs/17890557769>

Adds new integration [0xAHA/Midea-Heat-Pump-HA]

---

integration
plugin

Link to current release: <https://github.com/0xAHA/airtouch4_advanced/releases/tag/v2.0.3>
Link to successful HACS action (without the `ignore` key): <https://github.com/0xAHA/airtouch4_advanced/actions/runs/15359325809>
Link to successful hassfest action (if integration): <https://github.com/0xAHA/airtouch4_advanced/actions/runs/15359325805>

Adds new integration [0xAHA/airtouch4_advanced]

---

integration

Link to current release: https://github.com/spatecon/orcommconnect/releases/tag/v1.2.3
Link to successful HACS action (without the `ignore` key): https://github.com/spatecon/orcommconnect/actions/runs/18189920223/job/51782538885
Link to successful hassfest action (if integration): https://github.com/spatecon/orcommconnect/actions/runs/18179148240

Adds new integration [spatecon/orcommconnect]

---

integration

Link to current release: https://github.com/pytoyoda/ha_toyota/releases/tag/v2.0.17
Link to successful HACS action (without the `ignore` key): https://github.com/pytoyoda/ha_toyota/actions/runs/18191260151/job/51786663267
Link to successful hassfest action (if integration): https://github.com/pytoyoda/ha_toyota/actions/runs/18191260151/job/51786663247

Adds new integration [pytoyoda/ha_toyota]

---

plugin

Link to current release: https://github.com/timmaurice/lovelace-tankerkoenig-card/releases/tag/1.0.0
Link to successful HACS action (without the `ignore` key): https://github.com/timmaurice/lovelace-tankerkoenig-card/actions/runs/18305154768

Adds new plugin [timmaurice/lovelace-tankerkoenig-card]

---

integration

Link to current release: <https://github.com/DSorlov/snmp_printer/releases/tag/v1.0.0>
Link to successful HACS action (without the `ignore` key): <https://github.com/DSorlov/snmp_printer/actions/runs/18310467721/job/52137652896>
Link to successful hassfest action (if integration): <https://github.com/DSorlov/snmp_printer/actions/runs/18310467740/job/52137652157>

Adds new integration [DSorlov/snmp_printer]

---

integration

Link to current release: <https://github.com/FredrikM97/hass-surepetcare/releases/tag/v2.0.1>
Link to successful HACS action (without the `ignore` key): <https://github.com/FredrikM97/hass-surepetcare/actions/runs/18322442675>
Link to successful hassfest action (if integration): <https://github.com/FredrikM97/hass-surepetcare/actions/runs/18322442663>

Adds new integration [FredrikM97/hass-surepetcare]

---

blacklist
plugin
removed

Closes https://github.com/hacs/integration/issues/4661

Remove custom-cards/spotify-card
